### ISSUE TITLE
Registers multiple scroll listeners

### ISSUE THREAD

**Issue by developit** [vaneenige/uos#1]
Looks like you're missing a guard here:

https://github.com/vaneenige/uos/blob/9278e41ee589fb7d03246e11dc1b499eff5a3184/src/index.js#L24

I usually use the return value of push:

`if (l.push([a b c])===1) addEventListener(..)`

**Comment by vaneenige** [comment]
Fair point! I actually removed that in https://github.com/vaneenige/uos/commit/7a378b737f47805419dd1e5b15b08d8f5f8e2e43 as I found it only registers the listener once even when it's called multiple times.

Does it negatively impact performance when it's done like this or should I re-add the guard?
