### ISSUE TITLE
[Demo] 404 for ../dist/bundle.umd.js

### ISSUE THREAD

**Issue by totsteps** [vaneenige/uos#4]
As per ```package.json```, the build files are named as:
```javascript
"main": "dist/uos.mjs",
"unpkg": "dist/uos.umd.js",
```
But in ```demo/index.html```, the script tag is as below, resulting in ```404```.
```diff
- <script src="./dist/bundle.umd.js"></script>

modified       👇
+ <script src="../dist/bundle.umd.js"></script>
```

I have checked ```unpkg``` and could not find it published.

### I would love to fix this.

**Comment by lukeed** [comment]
Works for me if I just run `yarn start` – the paths are correct. Otherwise, yes, any other way will be broken

**Comment by totsteps** [comment]
My bad, missed ```watch``` script in ```package.json```.
